# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export GOBIN="$HOME/go/bin"
path=(
	$path
	$GOBIN
	$HOME/.local/bin
	$HOME/scripts
	$HOME/.cargo/bin
	$HOME/.sg
	$HOME/Library/pnpm
	/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin
)

# General env
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export XDG_CONFIG_HOME="$HOME/.config"
export CC=$(which gcc)

export TERM=screen-256color
export COLORTERM=truecolor
export EDITOR=nvim
export USE_EDITOR=$EDITOR
export VISUAL=$EDITOR
export MANPAGER='nvim +Man!'
export GPG_TTY=$(tty)

fpath=("$HOME/.config/zsh/functions" $fpath)

# History
HISTFILE=$HOME/.zsh_history
HISTSIZE=100000
SAVEHIST=100000
setopt append_history
setopt extended_history
setopt hist_verify
setopt share_history
setopt hist_ignore_dups
setopt inc_append_history

# Directory Options
setopt auto_pushd
setopt pushd_ignore_dups
setopt pushd_silent
setopt extended_glob

# Emacs keybindings
# for more info, man zshzle
bindkey -e

setopt INTERACTIVE_COMMENTS

# FZF options
export FZF_CTRL_T_COMMAND='fre --sorted'
export FZF_CTRL_T_OPTS='--tiebreak=index --no-sort --bind tab:down --bind shift-tab:up'
source "$XDG_CONFIG_HOME/zsh/fzf-key-bindings.zsh"

# Update fre on directory change
fre_chpwd() {
    fre --add "$(realpath "$(pwd)")"
}
typeset -gaU chpwd_functions
chpwd_functions+=fre_chpwd

. "$HOME/.nix-profile/share/asdf-vm/asdf.sh"
